export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SPINNER_ON = 'SPINNER_ON';
export const SPINNER_OFF = 'SPINNER_OFF';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const DELETE_CAR_SUCCESS = 'DELETE_SUCCESS';
export const EDIT_CAR_SUCCESS = 'EDIT_CAR_SUCCESS';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const START_EDITING = 'START_EDITING';
export const DONE_EDITING = 'DONE_EDITING';

